kind: Secret
apiVersion: v1
metadata:
  name: openapi-api-key
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  DEVSPACES_API_KEY: MzkxN2MwNTlmNmFlMDY2ZWIyYjQ1OTEyMjM0YzYxZjI=
type: Opaque
