kind: Secret
apiVersion: v1
metadata:
  name: openapi-api-key
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
stringData:
  DEVSPACES_API_KEY: devspaces
  OPENAI_API_KEY: TOKEN
  OPENAI_API_BASE: URL_OPENIA
  LLM_SERVER_ID: llama-3-2-3b
  LLM_SERVER_TOKEN: TOKEN
  LLM_SERVER_URL: URL_OPENIA
  RA_AID_PROVIDER: openai
  RA_AID_MODEL: llama-3-2-3b
  RA_AID_BACKEND: openai
  MCP_HEADERS: '{"backstage-actions": {"Authorization": "Bearer backstage"}}'
type: Opaque
