apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: coolstore
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB_USERNAME: postgresUser
  KC_DB_PASSWORD: postgresPW

