apiVersion: v1
kind: ConfigMap
metadata:
  name: wildfly-config
  namespace: coolstore
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgresDB
  KEYCLOAK_URL: http://keycloak:8081

